# -*- coding: utf-8 -*-
"""Playcatch

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EgoyWe-TzN9ctH9uONxQDyWJ5Zxk-4NJ
"""

pip install torch transformers gradio datasets huggingface_hub

import torch
import pandas as pd
import json
import re
import random
from transformers import pipeline
import gradio as gr

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

"""Sentiment-Analyse-Modell laden"""

sentiment_analysator = pipeline(
    "sentiment-analysis",
    model="nlptown/bert-base-multilingual-uncased-sentiment",
    device=device
)

"""
TEIL 2: DATENBANK (DATENBANK - PLAYCATCH)
"""

musik_katalog = [
    {"artist": "Ivete Sangalo", "title": "Sorte Grande", "lyric": "A minha sorte grande foi você cair do céu..."},
    {"artist": "Adele", "title": "Someone Like You", "lyric": "Never mind, I'll find someone like you..."},
    {"artist": "Linkin Park", "title": "In the End", "lyric": "I tried so hard and got so far..."},
    {"artist": "Pharrell Williams", "title": "Happy", "lyric": "Because I'm happy! Clap along..."},
    {"artist": "Legião Urbana", "title": "Vento no Litoral", "lyric": "De tarde quero descansar, ver se o vento ainda está forte."}
]

def text_reinigen(text):
    text = text.lower()
    text = re.sub(r'[^\w\s]', '', text)
    return text.strip()

# Verarbeitung der Daten
verarbeitete_daten = []
for item in musik_katalog:
    clean_lyric = text_reinigen(item['lyric'])
    res = sentiment_analysator(clean_lyric)[0]

    # Mapping der Sterne auf Stimmungen (Vibes)
    if res['label'] in ['1 star', '2 stars']:
        vibe = "Melancholisch/Traurig"
    elif res['label'] == '3 stars':
        vibe = "Neutral/Ruhig"
    else:
        vibe = "Glücklich/Energetisch"

    verarbeitete_daten.append({
        "artist": item['artist'],
        "title": item['title'],
        "stimmung": vibe
    })

df_musik = pd.DataFrame(verarbeitete_daten)

"""TEIL 3: DER PLAYCATCH BOT"""

class PlaycatchBot:
    def __init__(self):
        self.letzte_stimmung = None

    def generiere_antwort(self, benutzer_nachricht):
        # Stimmung analysieren
        analyse = sentiment_analysator(benutzer_nachricht)[0]
        label = analyse['label']

        if label in ['1 star', '2 stars']:
            aktuelle_vibe = "Melancholisch/Traurig"
        elif label == '3 stars':
            aktuelle_vibe = "Neutral/Ruhig"
        else:
            aktuelle_vibe = "Glücklich/Energetisch"

        # Musik suchen
        optionen = df_musik[df_musik['stimmung'] == aktuelle_vibe]

        if not optionen.empty:
            auswahl = optionen.sample(n=1).iloc[0]
            self.letzte_stimmung = aktuelle_vibe

            antwort = f"🤖 Ich spüre eine **{aktuelle_vibe}** Stimmung in deiner Nachricht.\n"
            antwort += f"Empfehlung: **{auswahl['title']}** von **{auswahl['artist']}**."
        else:
            antwort = "🤖 Entschuldigung, ich habe noch keine Musik für diese Stimmung im Katalog."

        return antwort

"""TEIL 4: EXECUTION"""

if __name__ == "__main__":
    bot = PlaycatchBot()
    print("--- 🎧 Willkommen bei Playcatch AI ---")
    print("Schreibe 'exit', um das Programm zu beenden.")

    while True:
        nutzer_eingabe = input("\nWie fühlst du dich heute? ")

        if nutzer_eingabe.lower() == 'exit':
            print("Auf Wiedersehen! Genießen Sie Ihre Musik. 🎶")
            break

        ergebnis = bot.generiere_antwort(nutzer_eingabe)
        print(ergebnis)